import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../dist/', import.meta.url));
const destination = path.join(root, 'precache-manifest.js');
async function list(dir) {
  const result = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue;
    const file = path.join(dir, entry.name);
    if (entry.isDirectory()) result.push(...await list(file));
    else if (entry.isFile() && !['sw.js', 'precache-manifest.js'].includes(entry.name)) result.push(file);
  }
  return result;
}
const files = [];
const versionHash = createHash('sha256');
versionHash.update(await readFile(path.join(root, 'sw.js')));
for (const file of (await list(root)).sort()) {
  const data = await readFile(file);
  const relative = path.relative(root, file).split(path.sep).join('/');
  const digest = createHash('sha256').update(data).digest('base64');
  files.push({ path: relative, integrity: `sha256-${digest}`, bytes: data.length });
  versionHash.update(relative + '\0' + digest + '\n');
}
const version = versionHash.digest('hex').slice(0, 20);
const output = `// Generated by npm run prepare:offline. Do not edit by hand.\nself.UNIVERSE_PRECACHE = ${JSON.stringify({ version, files }, null, 2)};\n`;
if (process.argv.includes('--check')) {
  let actual;
  try { actual = await readFile(destination, 'utf8'); } catch { /* reported below */ }
  if (actual !== output) {
    console.error('Offline snapshot is outdated. Run npm run prepare:offline.');
    process.exitCode = 1;
  } else console.log(`Offline snapshot verified: ${files.length} files, ${version}`);
} else {
  await writeFile(destination, output, 'utf8');
  console.log(`Offline snapshot prepared: ${files.length} files, ${(files.reduce((n, f) => n + f.bytes, 0) / 1024 / 1024).toFixed(1)} MiB, ${version}`);
}
